version: '3.8'

services:
  app:
    image: ivanhd/go-women_center:prod
    env_file:
      - .env
    networks:
      - network_go_women_center
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8-debian
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          '$$MYSQL_USER',
          '-p $$MYSQL_ROOT_PASSWORD',
        ]
      timeout: 20s
      retries: 10
    networks:
      - network_go_women_center
    ports:
      - 5432:5432
    volumes:
      - ./db/backup:/var/lib/mysql

networks:
  network_go_women_center:
    driver: bridge
